### ISSUE TITLE
UnboundLocalError: local variable 'aid' referenced before assignment

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#26]
```
Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 260, in wrapped_done
  File "/.local/share/Anki2/addons21/472573498/reviewing_utils.py", line 198, in _show_card
    mw.reviewer._showQuestion()
  File "aqt.reviewer", line 378, in _showQuestion
  File "aqt.sound", line 150, in play_tags
  File "aqt.sound", line 209, in _play_next_if_idle
  File "/.local/share/Anki2/addons21/939347702/player.py", line 286, in queueExternalAV
    queueExternal(path)
  File "/.local/share/Anki2/addons21/939347702/player.py", line 301, in queueExternal
    ret = playVideoClip(path.filename if av_player else path)
  File "/.local/share/Anki2/addons21/939347702/player.py", line 267, in playVideoClip
    args += ["--aid={}".format(aid)]
UnboundLocalError: local variable 'aid' referenced before assignment
```

**Comment by aleksejrs** [comment]
removed the try/except:
```
  File "/.local/share/Anki2/addons21/939347702/player.py", line 257, in playVideoClip
    aid = config["~media"][video_id]["audio_id"]
KeyError: '~media'
```

**Comment by kelciour** [comment]
Thank you! I've pushed an update!
